name: chisel
description: A Dart library for managing PostgreSQL databases with ease.
version: 1.2.2
homepage: https://asdaproject.com/
repository: https://github.com/asda-projects/chisel
issue_tracker: https://github.com/asda-projects/chisel/issu

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  postgres: ">=3.4.0 <3.4.5"
  logging: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
