class Table {
  final String name;
  final List<Column> columns;

  Table({required this.name, required this.columns});

  bool hasColumn(String columnName) {
    return columns.any((col) => col.name == columnName);
  }
}

class Column {
  final String name;
  final String? type;
  final String? foreignTable;
  final String? foreignColumn;
  final bool isAutoGenerated;

  const Column({
    required this.name,
    required this.type,
    this.foreignTable,
    this.foreignColumn,
    this.isAutoGenerated = false, // Default to false
  });
}

class ForeignKey {
  final String table;
  final String column;

  const ForeignKey({
    required this.table,
    required this.column,
  });
}
